#!/bin/bash

echo "-----------------------------------------------------------------------"
echo "-----------------------------------------------------------------------"
echo "-----------------------------------------------------------------------"

echo ""
python3.5 properties.py demofile.txt
cat propertiesLogFile.txt
echo ""
cat propertiesOutput.txt
echo ""

echo ""
python3.5 properties.py DFA1.txt
cat propertiesLogFile.txt
echo ""
cat propertiesOutput.txt
echo ""
cat DFA1-out.txt
echo ""

echo ""
python3.5 properties.py DFA2.txt
cat propertiesLogFile.txt
echo ""
cat propertiesOutput.txt
echo ""
cat DFA2-out.txt
echo ""

echo ""
python3.5 properties.py DFA3.txt
cat propertiesLogFile.txt
echo ""
cat propertiesOutput.txt
echo ""
cat DFA3-out.txt
echo ""

python3.5 properties.py DFA1.txt
cat DFA1-out.txt
python3.5 properties.py DFA2.txt
cat DFA2-out.txt
python3.5 properties.py DFA3.txt
cat DFA3-out.txt
python3.5 properties.py DFA4.txt
cat DFA4-out.txt
python3.5 properties.py DFA5.txt
cat DFA5-out.txt
python3.5 properties.py DFA6.txt
cat DFA6-out.txt
python3.5 properties.py DFA7.txt
cat DFA7-out.txt
python3.5 properties.py DFA8.txt
cat DFA8-out.txt
